use crate::error::{Error, Result};
use crate::model::{CodeBlock, CodeSource, Dependency, DependencyKind, SkillSpec};
use std::collections::{BTreeMap, BTreeSet};
use std::fs;
use std::path::Path;

#[derive(Clone, Debug)]
struct LedgerEntry {
    id: String,
    ecosystem: String,
    authority: String,
    source: String,
    reason: String,
    local_status: String,
    required_for: Vec<String>,
    degraded_without: bool,
    risk: String,
    install: String,
}

pub fn materialize(spec: &SkillSpec, out_dir: &Path) -> Result<()> {
    if !out_dir.as_os_str().is_empty() {
        fs::create_dir_all(out_dir).map_err(|source| Error::Write {
            path: out_dir.to_path_buf(),
            source,
        })?;
    }
    let path = out_dir.join("deps.toml");
    let ledger = render(spec);
    fs::write(&path, ledger).map_err(|source| Error::Write { path, source })?;
    Ok(())
}

fn render(spec: &SkillSpec) -> String {
    let entries = entries(spec);
    let mut output = String::new();
    output.push_str("# Generated by `skillspec import-skill`.\n");
    output.push_str("# Review before proof, install, or release. Do not delete missing dependencies to make QA pass.\n");
    output.push_str("schema_version = 1\n");
    output.push_str("generated_by = \"skillspec import-skill\"\n");
    output.push_str("review_required = true\n");
    output.push_str(&format!("dependency_count = {}\n", entries.len()));
    output.push('\n');

    if entries.is_empty() {
        output.push_str("# No dependencies were inferred mechanically. Review SKILL.md, references, helper scripts, command examples, and package manifests before proof.\n");
        return output;
    }

    for entry in entries {
        output.push_str("[[dependency]]\n");
        output.push_str(&format!("id = {}\n", toml_string(&entry.id)));
        output.push_str(&format!("ecosystem = {}\n", toml_string(&entry.ecosystem)));
        output.push_str(&format!("authority = {}\n", toml_string(&entry.authority)));
        output.push_str(&format!("source = {}\n", toml_string(&entry.source)));
        output.push_str(&format!("reason = {}\n", toml_string(&entry.reason)));
        output.push_str(&format!(
            "local_status = {}\n",
            toml_string(&entry.local_status)
        ));
        output.push_str(&format!(
            "required_for = {}\n",
            toml_array(&entry.required_for)
        ));
        output.push_str(&format!("degraded_without = {}\n", entry.degraded_without));
        output.push_str(&format!("risk = {}\n", toml_string(&entry.risk)));
        output.push_str(&format!("install = {}\n\n", toml_string(&entry.install)));
    }

    output
}

fn entries(spec: &SkillSpec) -> Vec<LedgerEntry> {
    let mut entries = BTreeMap::<String, LedgerEntry>::new();
    for (id, dependency) in &spec.dependencies {
        if id == "dependency_ledger" {
            continue;
        }
        let entry = entry_from_dependency(id, dependency);
        entries.insert(key(&entry), entry);
    }

    for (code_id, block) in &spec.code {
        let CodeSource::Inline(source) = &block.source else {
            continue;
        };
        let source_ref = code_source_ref(block);
        for package in code_package_dependencies(&block.language, &source.inline) {
            let entry = entry_from_code_import(&package, &block.language, code_id, &source_ref);
            entries.insert(key(&entry), entry);
        }
    }

    entries.into_values().collect()
}

fn entry_from_dependency(id: &str, dependency: &Dependency) -> LedgerEntry {
    let ecosystem = match dependency.kind {
        DependencyKind::Cli => "cli",
        DependencyKind::Package => "package",
        DependencyKind::File => "file",
        DependencyKind::Env => "env",
        DependencyKind::Service => "service",
        DependencyKind::Adapter => "adapter",
        DependencyKind::Browser => "browser",
    }
    .to_owned();
    let dependency_name = dependency
        .command
        .as_deref()
        .or(dependency.path.as_deref())
        .or(dependency.env.as_deref())
        .unwrap_or(id);
    LedgerEntry {
        id: dependency_name.to_owned(),
        ecosystem,
        authority: "inferred".to_owned(),
        source: "skillspec import-skill".to_owned(),
        reason: dependency.description.clone().unwrap_or_else(|| {
            format!("Inferred dependency from imported skill material: {dependency_name}")
        }),
        local_status: "unknown".to_owned(),
        required_for: vec!["imported_runtime".to_owned()],
        degraded_without: true,
        risk: "Mechanically inferred dependency; provision only after source review and user approval."
            .to_owned(),
        install: String::new(),
    }
}

fn entry_from_code_import(
    package: &str,
    language: &str,
    code_id: &str,
    source_ref: &str,
) -> LedgerEntry {
    let language = language.trim().to_ascii_lowercase();
    let (ecosystem, install) = if matches!(language.as_str(), "python" | "py") {
        ("python", format!("pip install {package}"))
    } else {
        ("javascript", format!("npm install {package}"))
    };
    LedgerEntry {
        id: package.to_owned(),
        ecosystem: ecosystem.to_owned(),
        authority: "script_import".to_owned(),
        source: source_ref.to_owned(),
        reason: format!("Imported by fenced code block {code_id}."),
        local_status: "unknown".to_owned(),
        required_for: vec![code_id.to_owned(), "imported_code".to_owned()],
        degraded_without: true,
        risk: "Third-party package imported by source code; install only after source review and user approval."
            .to_owned(),
        install,
    }
}

fn key(entry: &LedgerEntry) -> String {
    format!("{}:{}", entry.ecosystem, entry.id)
}

fn code_source_ref(block: &CodeBlock) -> String {
    let Some(provenance) = &block.provenance else {
        return "imported code block".to_owned();
    };
    let source = provenance
        .resource
        .as_deref()
        .or(provenance.import.as_deref())
        .unwrap_or("imported code block");
    match provenance.line_start {
        Some(line) => format!("{source}:{line}"),
        None => source.to_owned(),
    }
}

fn code_package_dependencies(language: &str, source: &str) -> Vec<String> {
    match language.trim().to_ascii_lowercase().as_str() {
        "python" | "py" => python_import_dependencies(source),
        "javascript" | "js" | "typescript" | "ts" => javascript_import_dependencies(source),
        _ => Vec::new(),
    }
}

fn python_import_dependencies(source: &str) -> Vec<String> {
    let mut packages = BTreeSet::new();
    for line in source.lines() {
        let trimmed = line.split('#').next().unwrap_or("").trim();
        if let Some(rest) = trimmed.strip_prefix("import ") {
            for part in rest.split(',') {
                if let Some(package) = python_package_name(part) {
                    packages.insert(package);
                }
            }
        } else if let Some(rest) = trimmed.strip_prefix("from ") {
            if let Some(package) = rest.split_whitespace().next().and_then(python_package_name) {
                packages.insert(package);
            }
        }
    }
    packages.into_iter().collect()
}

fn python_package_name(import: &str) -> Option<String> {
    let name = import
        .split_whitespace()
        .next()
        .unwrap_or("")
        .split('.')
        .next()
        .unwrap_or("")
        .trim();
    if name.is_empty() || name.starts_with('.') || is_python_stdlib(name) {
        None
    } else {
        Some(name.to_owned())
    }
}

fn is_python_stdlib(name: &str) -> bool {
    matches!(
        name,
        "argparse"
            | "asyncio"
            | "base64"
            | "collections"
            | "contextlib"
            | "csv"
            | "dataclasses"
            | "datetime"
            | "decimal"
            | "enum"
            | "functools"
            | "glob"
            | "hashlib"
            | "io"
            | "itertools"
            | "json"
            | "logging"
            | "math"
            | "os"
            | "pathlib"
            | "random"
            | "re"
            | "shutil"
            | "statistics"
            | "subprocess"
            | "sys"
            | "tempfile"
            | "textwrap"
            | "time"
            | "typing"
            | "urllib"
            | "uuid"
    )
}

fn javascript_import_dependencies(source: &str) -> Vec<String> {
    let mut packages = BTreeSet::new();
    for line in source.lines() {
        for package in quoted_packages_after(line, " from ") {
            packages.insert(package);
        }
        for package in quoted_packages_after(line, "require(") {
            packages.insert(package);
        }
        for package in quoted_packages_after(line, "import(") {
            packages.insert(package);
        }
        let trimmed = line.trim_start();
        if let Some(rest) = trimmed.strip_prefix("import ") {
            for package in quoted_packages_after(rest, "") {
                packages.insert(package);
            }
        }
    }
    packages.into_iter().collect()
}

fn quoted_packages_after(line: &str, marker: &str) -> Vec<String> {
    if marker.is_empty() {
        return quoted_package(line).into_iter().collect();
    }

    let mut packages = Vec::new();
    let mut offset = 0;
    while let Some(marker_index) = line[offset..].find(marker) {
        let package_start = offset + marker_index + marker.len();
        if let Some(package) = quoted_package(&line[package_start..]) {
            packages.push(package);
        }
        offset = package_start.saturating_add(1);
    }
    packages
}

fn quoted_package(source: &str) -> Option<String> {
    let source = source.trim_start();
    let quote = source.chars().next()?;
    if quote != '"' && quote != '\'' {
        return None;
    }
    let rest = &source[quote.len_utf8()..];
    let end = rest.find(quote)?;
    normalize_js_package(&rest[..end])
}

fn normalize_js_package(specifier: &str) -> Option<String> {
    if specifier.starts_with('.') || specifier.starts_with('/') || specifier.starts_with("node:") {
        return None;
    }
    if specifier.starts_with('@') {
        let mut parts = specifier.split('/');
        let scope = parts.next()?;
        let package = parts.next()?;
        Some(format!("{scope}/{package}"))
    } else {
        let package = specifier.split('/').next()?;
        (!is_js_builtin(package)).then(|| package.to_owned())
    }
}

fn is_js_builtin(name: &str) -> bool {
    matches!(
        name,
        "assert"
            | "buffer"
            | "child_process"
            | "crypto"
            | "events"
            | "fs"
            | "http"
            | "https"
            | "module"
            | "os"
            | "path"
            | "process"
            | "querystring"
            | "stream"
            | "timers"
            | "url"
            | "util"
            | "zlib"
    )
}

fn toml_string(value: &str) -> String {
    format!("\"{}\"", value.replace('\\', "\\\\").replace('"', "\\\""))
}

fn toml_array(values: &[String]) -> String {
    let values = values
        .iter()
        .map(|value| toml_string(value))
        .collect::<Vec<_>>()
        .join(", ");
    format!("[{values}]")
}
