use crate::error::{Error, Result};
use crate::model::{
    Artifact, ArtifactKind, CodeBlock, CodeSource, Dependency, DependencyCheck, DependencyKind,
    SkillSpec,
};
use std::collections::{BTreeMap, BTreeSet};
use std::fs;
use std::path::Path;

pub const DEPENDENCY_LEDGER_ID: &str = "dependency_ledger";
pub const DEPS_TOML_PATH: &str = "deps.toml";
pub const QUARANTINED_DEPENDENCY_METADATA_KEY: &str = "import_quarantined_dependency_candidates";

#[derive(Clone, Debug)]
struct LedgerEntry {
    id: String,
    ecosystem: String,
    authority: String,
    source: String,
    reason: String,
    local_status: String,
    required_for: Vec<String>,
    degraded_without: bool,
    risk: String,
    install: String,
}

#[derive(Clone, Debug)]
struct QuarantinedDependency {
    id: String,
    source: String,
    reason: String,
}

#[derive(Clone, Debug, Eq, PartialEq, Ord, PartialOrd)]
enum CodePackageDependency {
    Accepted(String),
    Quarantined { id: String, reason: String },
}

pub fn dependency(description: impl Into<String>) -> Dependency {
    Dependency {
        kind: DependencyKind::File,
        description: Some(description.into()),
        command: None,
        path: Some(DEPS_TOML_PATH.to_owned()),
        env: None,
        check: Some(DependencyCheck {
            command: None,
            path: Some(DEPS_TOML_PATH.to_owned()),
            env: None,
        }),
        permission: None,
        provision: None,
    }
}

pub fn artifact(description: impl Into<String>) -> Artifact {
    Artifact {
        kind: ArtifactKind::File,
        description: Some(description.into()),
        path: Some(DEPS_TOML_PATH.to_owned()),
        schema: None,
        produced_by: Vec::new(),
        consumed_by: Vec::new(),
    }
}

pub fn materialize(spec: &SkillSpec, out_dir: &Path) -> Result<()> {
    materialize_with_generator(spec, out_dir, "skillspec import-skill")
}

pub fn materialize_with_generator(spec: &SkillSpec, out_dir: &Path, generator: &str) -> Result<()> {
    if !out_dir.as_os_str().is_empty() {
        fs::create_dir_all(out_dir).map_err(|source| Error::Write {
            path: out_dir.to_path_buf(),
            source,
        })?;
    }
    let path = out_dir.join(DEPS_TOML_PATH);
    let ledger = render(spec, generator);
    fs::write(&path, ledger).map_err(|source| Error::Write { path, source })?;
    Ok(())
}

fn render(spec: &SkillSpec, generator: &str) -> String {
    let (entries, quarantined) = entries(spec, generator);
    let mut output = String::new();
    output.push_str(&format!("# Generated by `{generator}`.\n"));
    output.push_str("# Review before proof, install, or release. Do not delete missing dependencies to make QA pass.\n");
    output.push_str("# Dependency extraction is evidence-based: executable commands become cli dependencies, declared services become service/api dependencies, package-manager evidence becomes package dependencies, and code examples stay reference-only unless promoted during review.\n");
    output.push_str("schema_version = 1\n");
    output.push_str(&format!("generated_by = {}\n", toml_string(generator)));
    output.push_str("review_required = true\n");
    output.push_str(&format!("dependency_count = {}\n", entries.len()));
    output.push_str(&format!("quarantined_count = {}\n", quarantined.len()));
    output.push('\n');

    if entries.is_empty() {
        output.push_str("# No dependencies were inferred mechanically. Review SKILL.md, references, helper scripts, command examples, and package manifests before proof.\n");
    }
    if !quarantined.is_empty() {
        output.push_str("# Quarantined candidates are not dependencies and must not block install until reviewed.\n");
        for candidate in &quarantined {
            output.push_str("[[quarantined_dependency]]\n");
            output.push_str(&format!("id = {}\n", toml_string(&candidate.id)));
            output.push_str(&format!("source = {}\n", toml_string(&candidate.source)));
            output.push_str(&format!("reason = {}\n\n", toml_string(&candidate.reason)));
        }
    }
    if entries.is_empty() {
        return output;
    }

    for entry in entries {
        output.push_str("[[dependency]]\n");
        output.push_str(&format!("id = {}\n", toml_string(&entry.id)));
        output.push_str(&format!("ecosystem = {}\n", toml_string(&entry.ecosystem)));
        output.push_str(&format!("authority = {}\n", toml_string(&entry.authority)));
        output.push_str(&format!("source = {}\n", toml_string(&entry.source)));
        output.push_str(&format!("reason = {}\n", toml_string(&entry.reason)));
        output.push_str(&format!(
            "local_status = {}\n",
            toml_string(&entry.local_status)
        ));
        output.push_str(&format!(
            "required_for = {}\n",
            toml_array(&entry.required_for)
        ));
        output.push_str(&format!("degraded_without = {}\n", entry.degraded_without));
        output.push_str(&format!("risk = {}\n", toml_string(&entry.risk)));
        output.push_str(&format!("install = {}\n\n", toml_string(&entry.install)));
    }

    output
}

fn entries(spec: &SkillSpec, generator: &str) -> (Vec<LedgerEntry>, Vec<QuarantinedDependency>) {
    let mut entries = BTreeMap::<String, LedgerEntry>::new();
    let mut quarantined = Vec::<QuarantinedDependency>::new();
    for (id, dependency) in &spec.dependencies {
        if id == DEPENDENCY_LEDGER_ID {
            continue;
        }
        let entry = entry_from_dependency(id, dependency, generator);
        insert_or_quarantine(&mut entries, &mut quarantined, entry);
    }

    for (code_id, block) in &spec.code {
        let CodeSource::Inline(source) = &block.source else {
            continue;
        };
        let source_ref = code_source_ref(block);
        for candidate in code_package_dependencies(&block.language, &source.inline) {
            match candidate {
                CodePackageDependency::Accepted(package) => {
                    let entry =
                        entry_from_code_import(&package, &block.language, code_id, &source_ref);
                    insert_or_quarantine(&mut entries, &mut quarantined, entry);
                }
                CodePackageDependency::Quarantined { id, reason } => {
                    quarantined.push(QuarantinedDependency {
                        id,
                        source: source_ref.clone(),
                        reason,
                    });
                }
            }
        }
    }
    quarantined.extend(metadata_quarantined_dependencies(spec));

    (entries.into_values().collect(), quarantined)
}

fn metadata_quarantined_dependencies(spec: &SkillSpec) -> Vec<QuarantinedDependency> {
    let Some(serde_yaml::Value::Sequence(candidates)) =
        spec.metadata.get(QUARANTINED_DEPENDENCY_METADATA_KEY)
    else {
        return Vec::new();
    };
    candidates
        .iter()
        .filter_map(|candidate| {
            let serde_yaml::Value::Mapping(mapping) = candidate else {
                return None;
            };
            let id = yaml_string(mapping, "id")?;
            let source = yaml_string(mapping, "source")
                .unwrap_or_else(|| "skillspec import-skill".to_owned());
            let reason = yaml_string(mapping, "reason").unwrap_or_else(|| {
                "Rejected mechanically inferred dependency candidate; preserve for review only."
                    .to_owned()
            });
            Some(QuarantinedDependency { id, source, reason })
        })
        .collect()
}

fn yaml_string(mapping: &serde_yaml::Mapping, key: &str) -> Option<String> {
    mapping
        .get(serde_yaml::Value::String(key.to_owned()))
        .and_then(|value| value.as_str())
        .map(str::to_owned)
}

fn insert_or_quarantine(
    entries: &mut BTreeMap<String, LedgerEntry>,
    quarantined: &mut Vec<QuarantinedDependency>,
    entry: LedgerEntry,
) {
    if dependency_id_is_valid(&entry.id) {
        entries.insert(key(&entry), entry);
    } else {
        quarantined.push(QuarantinedDependency {
            id: entry.id,
            source: entry.source,
            reason: "Rejected mechanically inferred dependency id; preserve for review only."
                .to_owned(),
        });
    }
}

fn entry_from_dependency(id: &str, dependency: &Dependency, generator: &str) -> LedgerEntry {
    let ecosystem = match dependency.kind {
        DependencyKind::Cli => "cli",
        DependencyKind::Package => "package",
        DependencyKind::File => "file",
        DependencyKind::Env => "env",
        DependencyKind::Service => "service",
        DependencyKind::Adapter => "adapter",
        DependencyKind::Browser => "browser",
    }
    .to_owned();
    let dependency_name = dependency
        .command
        .as_deref()
        .or(dependency.path.as_deref())
        .or(dependency.env.as_deref())
        .unwrap_or(id);
    let authority = match dependency.kind {
        DependencyKind::Cli if dependency.command.is_some() => "command_evidence",
        DependencyKind::Service => "api_required",
        DependencyKind::Package => "inferred_review_required",
        _ => "declared",
    };
    LedgerEntry {
        id: dependency_name.to_owned(),
        ecosystem,
        authority: authority.to_owned(),
        source: generator.to_owned(),
        reason: dependency.description.clone().unwrap_or_else(|| {
            format!("Inferred dependency from {generator}: {dependency_name}")
        }),
        local_status: "unknown".to_owned(),
        required_for: vec!["skill_runtime".to_owned()],
        degraded_without: true,
        risk: "Mechanically inferred dependency; provision only after source review and user approval."
            .to_owned(),
        install: String::new(),
    }
}

fn entry_from_code_import(
    package: &str,
    language: &str,
    code_id: &str,
    source_ref: &str,
) -> LedgerEntry {
    let language = language.trim().to_ascii_lowercase();
    let (ecosystem, install) = if matches!(language.as_str(), "python" | "py") {
        ("python", format!("pip install {package}"))
    } else {
        ("javascript", format!("npm install {package}"))
    };
    LedgerEntry {
        id: package.to_owned(),
        ecosystem: ecosystem.to_owned(),
        authority: "reference_import".to_owned(),
        source: source_ref.to_owned(),
        reason: format!(
            "Imported by fenced code block {code_id}; treat as reference/example evidence until reviewed as skill runtime."
        ),
        local_status: "unknown".to_owned(),
        required_for: vec![code_id.to_owned(), "reference_example".to_owned()],
        degraded_without: false,
        risk: "Reference/example package import; do not block install unless semantic review promotes it to skill runtime."
            .to_owned(),
        install,
    }
}

fn key(entry: &LedgerEntry) -> String {
    format!("{}:{}", entry.ecosystem, entry.id)
}

fn code_source_ref(block: &CodeBlock) -> String {
    let Some(provenance) = &block.provenance else {
        return "imported code block".to_owned();
    };
    let source = provenance
        .resource
        .as_deref()
        .or(provenance.import.as_deref())
        .unwrap_or("imported code block");
    match provenance.line_start {
        Some(line) => format!("{source}:{line}"),
        None => source.to_owned(),
    }
}

fn code_package_dependencies(language: &str, source: &str) -> Vec<CodePackageDependency> {
    match language.trim().to_ascii_lowercase().as_str() {
        "python" | "py" => python_import_dependencies(source),
        "javascript" | "js" | "typescript" | "ts" => javascript_import_dependencies(source),
        _ => Vec::new(),
    }
}

fn python_import_dependencies(source: &str) -> Vec<CodePackageDependency> {
    let mut packages = BTreeSet::<CodePackageDependency>::new();
    for line in source.lines() {
        let trimmed = line.split('#').next().unwrap_or("").trim();
        if let Some(rest) = trimmed.strip_prefix("import ") {
            for part in rest.split(',') {
                if let Some(package) = python_package_candidate(part) {
                    packages.insert(package);
                }
            }
        } else if let Some(rest) = trimmed.strip_prefix("from ") {
            if let Some(package) = rest
                .split_whitespace()
                .next()
                .and_then(python_package_candidate)
            {
                packages.insert(package);
            }
        }
    }
    packages.into_iter().collect()
}

fn python_package_candidate(import: &str) -> Option<CodePackageDependency> {
    let name = import
        .split_whitespace()
        .next()
        .unwrap_or("")
        .split('.')
        .next()
        .unwrap_or("")
        .trim();
    if name.is_empty() || name.starts_with('.') || is_python_stdlib(name) {
        None
    } else if dependency_id_is_valid(name) {
        Some(CodePackageDependency::Accepted(name.to_owned()))
    } else {
        Some(CodePackageDependency::Quarantined {
            id: name.to_owned(),
            reason: "Rejected package-like token from Python import syntax; review as prose/example evidence only.".to_owned(),
        })
    }
}

fn is_python_stdlib(name: &str) -> bool {
    matches!(
        name,
        "argparse"
            | "asyncio"
            | "base64"
            | "collections"
            | "contextlib"
            | "csv"
            | "dataclasses"
            | "datetime"
            | "decimal"
            | "enum"
            | "functools"
            | "glob"
            | "hashlib"
            | "io"
            | "itertools"
            | "json"
            | "logging"
            | "math"
            | "os"
            | "pathlib"
            | "random"
            | "re"
            | "shutil"
            | "statistics"
            | "subprocess"
            | "sys"
            | "tempfile"
            | "textwrap"
            | "time"
            | "typing"
            | "urllib"
            | "uuid"
    )
}

fn javascript_import_dependencies(source: &str) -> Vec<CodePackageDependency> {
    let mut packages = BTreeSet::<CodePackageDependency>::new();
    for line in source.lines() {
        for package in quoted_packages_after(line, " from ") {
            packages.insert(package);
        }
        for package in quoted_packages_after(line, "require(") {
            packages.insert(package);
        }
        for package in quoted_packages_after(line, "import(") {
            packages.insert(package);
        }
        let trimmed = line.trim_start();
        if let Some(rest) = trimmed.strip_prefix("import ") {
            for package in quoted_packages_after(rest, "") {
                packages.insert(package);
            }
        }
    }
    packages.into_iter().collect()
}

fn quoted_packages_after(line: &str, marker: &str) -> Vec<CodePackageDependency> {
    if marker.is_empty() {
        return quoted_package(line).into_iter().collect();
    }

    let mut packages = Vec::new();
    let mut offset = 0;
    while let Some(marker_index) = line[offset..].find(marker) {
        let package_start = offset + marker_index + marker.len();
        if let Some(package) = quoted_package(&line[package_start..]) {
            packages.push(package);
        }
        offset = package_start.saturating_add(1);
    }
    packages
}

fn quoted_package(source: &str) -> Option<CodePackageDependency> {
    let source = source.trim_start();
    let quote = source.chars().next()?;
    if quote != '"' && quote != '\'' {
        return None;
    }
    let rest = &source[quote.len_utf8()..];
    let end = rest.find(quote)?;
    normalize_js_package(&rest[..end])
}

fn normalize_js_package(specifier: &str) -> Option<CodePackageDependency> {
    if specifier.starts_with('.') || specifier.starts_with('/') || specifier.starts_with("node:") {
        return None;
    }
    if specifier.starts_with('@') {
        let mut parts = specifier.split('/');
        let scope = parts.next()?;
        let package = parts.next()?;
        let candidate = format!("{scope}/{package}");
        if dependency_id_is_valid(&candidate) {
            Some(CodePackageDependency::Accepted(candidate))
        } else {
            Some(CodePackageDependency::Quarantined {
                id: candidate,
                reason: "Rejected package-like token from JavaScript import syntax; review as prose/example evidence only.".to_owned(),
            })
        }
    } else {
        let package = specifier.split('/').next()?;
        if is_js_builtin(package) {
            None
        } else if dependency_id_is_valid(package) {
            Some(CodePackageDependency::Accepted(package.to_owned()))
        } else {
            Some(CodePackageDependency::Quarantined {
                id: package.to_owned(),
                reason: "Rejected package-like token from JavaScript import syntax; review as prose/example evidence only.".to_owned(),
            })
        }
    }
}

fn dependency_id_is_valid(id: &str) -> bool {
    let id = id.trim();
    if id.is_empty()
        || id.len() > 128
        || id.chars().any(|char| char.is_ascii_uppercase())
        || id.starts_with('<')
        || id.ends_with('>')
        || id.ends_with('.')
        || id.starts_with('/')
        || id.ends_with('/')
        || id.contains(char::is_whitespace)
    {
        return false;
    }
    let lower = id.to_ascii_lowercase();
    if matches!(
        lower.as_str(),
        "optional"
            | "required"
            | "replace"
            | "table"
            | "default"
            | "defaults"
            | "false"
            | "true"
            | "custom"
            | "chrome"
            | "eof"
            | "get"
            | "post"
            | "put"
            | "patch"
            | "delete"
            | "head"
            | "options"
            | "trace"
            | "connect"
            | "have"
            | "me"
            | "quick"
    ) {
        return false;
    }
    if id.starts_with('_') || id.contains('<') || id.contains('>') {
        return false;
    }
    id.chars().all(|char| {
        char.is_ascii_alphanumeric() || matches!(char, '_' | '-' | '.' | '+' | '/' | '@')
    })
}

fn is_js_builtin(name: &str) -> bool {
    matches!(
        name,
        "assert"
            | "buffer"
            | "child_process"
            | "crypto"
            | "events"
            | "fs"
            | "http"
            | "https"
            | "module"
            | "os"
            | "path"
            | "process"
            | "querystring"
            | "stream"
            | "timers"
            | "url"
            | "util"
            | "zlib"
    )
}

fn toml_string(value: &str) -> String {
    format!("\"{}\"", value.replace('\\', "\\\\").replace('"', "\\\""))
}

fn toml_array(values: &[String]) -> String {
    let values = values
        .iter()
        .map(|value| toml_string(value))
        .collect::<Vec<_>>()
        .join(", ");
    format!("[{values}]")
}
